LottoPlus/Models/ErrorViewModel.cs
namespace LottoPlus.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LottoPlus/Controllers/HomeController.cs
using LottoPlus.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LottoPlus.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LottoPlus/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;

namespace LottoPlus.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

LottoPlus/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;

namespace LottoPlus.Controllers
{
    public class RegisterController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

LottoPlus/Views/Login/Index.cshtml
@{
    ViewBag.Title = "เข้าสู่ระบบ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- Login Area -->
<div class="log-reg-inner">
    <h2 class="title">
        Welcome to Lotto Plus
    </h2>
    <div class="main-content">
        <form action="#">
            <div class="form-group">
                <label>Your Email</label>
                <input type="email" class="my-form-control" placeholder="Enter Your Email">
            </div>
            <div class="form-group">
                <label>Password</label>
                <input type="text" class="my-form-control" placeholder="Enter Your Password">
            </div>
            <p class="f-pass">
                Forgot your password? <a href="#">recover password</a>
            </p>
            <div class="button-wrapper">
                <button type="submit" class="custom-button2">Sign In</button>
            </div>
            <div class="or log">
                <p>OR</p>
            </div>
            <div class="or-content">
                <p>Sign up with your email</p>
                <a href="#" class="or-btn">
                    <img src="assets/images/google.png" alt=""> Sign Up with
                    Google
                </a>
                <p class="or-signup">
                    Don't have an account? <a class="custom-button1" asp-controller="Register" asp-action="Index">
                        Sign up here
                    </a>
                </p>
            </div>
        </form>
    </div>
</div>
<!-- Login Area -->

LottoPlus/Views/Register/Index.cshtml
@{
    ViewBag.Title = "ลงทะเบียน";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- Register Area -->
<div class="log-reg-inner">
    <h2 class="title">
        Create an Account
    </h2>
    <div class="main-content">
        <form action="#">
            <div class="form-group">
                <label>Your Email</label>
                <input type="email" class="my-form-control" placeholder="Enter Your Email">
            </div>
            <div class="form-group">
                <label>Password</label>
                <input type="text" class="my-form-control" placeholder="Enter Your Password">
            </div>
            <div class="form-group">
                <label>Confirm Password</label>
                <input type="text" class="my-form-control"
                       placeholder="Enter Your Confirm Password">
            </div>
            <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id="customCheck1">
                <label class="custom-control-label" for="customCheck1">
                    I agree to the <a href="#">Terms, Privacy Policy and Fees</a>
                </label>
            </div>
            <div class="button-wrapper">
                <button type="submit" class="custom-button2">Register Now</button>
                <p class="or-signup">
                    Already have an account? <a href="#" data-toggle="modal"
                                                data-target="#loginModal">
                        Login
                    </a>
                </p>
            </div>
            <div class="or">
                <p>OR</p>
            </div>
            <div class="socials">
                <a href="#">
                    <i class="fab fa-facebook-f"></i>
                </a>
                <a href="#">
                    <i class="fab fa-twitter"></i>
                </a>
                <a href="#">
                    <i class="fab fa-google"></i>
                </a>
            </div>
        </form>
    </div>
</div>

<!-- Register Area -->

LottoPlus/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/css/all.min.css">
    <link rel="stylesheet" href="~/assets/css/magnific-popup.css">
    <link rel="stylesheet" href="~/assets/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/assets/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/assets/css/nice-select.css">
    <link rel="stylesheet" href="~/assets/css/bootstrap-popover-x.min.css">
    <link rel="stylesheet" href="~/assets/css/main.css">
    <link rel="stylesheet" href="~/assets/css/responsive.css">
    <link rel="shortcut icon" href="~/assets/images/favicon.png" type="image/x-icon">
    <title>@ViewData["Title"] - LottoPlus</title>
</head>
<body>
    <!-- ==========Preloader========== -->
    <div class="preloader">
        <div class="preloader-inner">
            <div class="preloader-icon">
                <span></span>
                <span></span>
            </div>
        </div>
    </div>
    <!-- ==========Preloader========== -->

    <!-- ==========Overlay========== -->
    <div class="overlay"></div>
    <a href="#" class="scrollToTop">
        <i class="fas fa-angle-up"></i>
    </a>
    <!-- ==========Overlay========== -->
    <!-- ==========Header-Section========== -->
    <header class="top-header">
        <div class="header-top-area">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="header-top-area-inner">
                            <a href="index.html" class="logo">
                                <img src="assets/images/logo.png" alt="">
                            </a>
                            <div class="right-area">
                                <div class="log-reg-area">
                                    <a class="custom-button1" asp-controller="Register" asp-action="Index">Register</a>
                                    <a  class="custom-button2" asp-controller="Login" asp-action="Index"> Log In</a>
                                </div>
                                <div class="cart-area">
                                    <div class="icon">
                                        <img src="assets/images/cart.png" alt="">
                                        <span>06</span>
                                    </div>
                                    <div class="amount">
                                        <h4 class="mony">$ 23.60</h4>
                                        <p>To checkout</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="header-section">
            <div class="container">
                <div class="header-wrapper">
                    <ul class="menu">
                        <li>
                            <a asp-controller="Home" asp-action="Index" class="active">ซื้อล็อตเตอรี่</a>
                        </li>                       
                    </ul>                  
                    <div class="header-bar d-lg-none">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- ==========Header-Section========== -->

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- ==========Newslater-Section========== -->
    <footer class="footer-section">
        <div class="container">
            <div class="footer-links">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="footer-top-area">
                            <div class="left">
                                <a href="#">
                                    <img src="assets/images/app_store_btn.png" alt="">
                                </a>
                                <a href="#">
                                    <img src="assets/images/goole_play_btn.png" alt="">
                                </a>
                            </div>
                            <div class="right">
                                <ul class="links">
                                    <li>
                                        <a href="#">About</a>
                                    </li>
                                    <li>
                                        <a href="#">FAQs</a>
                                    </li>
                                    <li>
                                        <a href="#">Contact</a>
                                    </li>
                                    <li>
                                        <a href="#">Terms of Service</a>
                                    </li>
                                    <li>
                                        <a href="#">Privacy</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="copyright-wrapper">
                <div class="row">
                    <div class="col-lg-12">
                        <hr class="hr2">
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6 align-self-center">
                        <div class="copyr-text">
                            <span>
                                Copyright © 2020.All Rights Reserved By
                            </span>
                            <a href="#">Fantra</a>
                        </div>
                    </div>
                    <div class="col-lg-6 align-self-center">
                        <ul class="footer-social-links">
                            <li>
                                <a href="#">
                                    <i class="fab fa-twitter"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="fab fa-facebook-f"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="fab fa-instagram"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="fab fa-dribbble"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- ==========Newslater-Section========== -->
    <script src="~/assets/js/jquery-3.3.1.min.js"></script>
    <script src="~/assets/js/modernizr-3.6.0.min.js"></script>
    <script src="~/assets/js/plugins.js"></script>
    <script src="~/assets/js/bootstrap.min.js"></script>
    <script src="~/assets/js/magnific-popup.min.js"></script>
    <script src="~/assets/js/owl.carousel.min.js"></script>
    <script src="~/assets/js/countdown.min.js"></script>
    <script src="~/assets/js/bootstrap-popover-x.min.js"></script>
    <script src="~/assets/js/amd.js"></script>
    <script src="~/assets/js/nice-select.js"></script>
    <script src="~/assets/js/main.js"></script>
    <script src="~/assets/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>